FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
ARG nameapp=GameStore 
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY $nameapp/*.csproj ./$nameapp/
RUN dotnet restore

# copy everything else and build app
COPY $nameapp/. ./$nameapp/
WORKDIR /app/$nameapp
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
EXPOSE 80
COPY --from=build /app/GameStore/out ./
ENTRYPOINT ["dotnet", "GameStore.dll"]
